{% set version = '1.1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ragtop
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ragtop_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ragtop/ragtop_{{ version }}.tar.gz
  sha256: a02c8b3b64e5b5e7a05ea4f690242eed75ae894a73cd143063daa3170e16ec6d

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-futile.logger >=1.4.1
    - r-limsolve >=1.5.5.1
  run:
    - r-base
    - r-futile.logger >=1.4.1
    - r-limsolve >=1.5.5.1

test:
  commands:
    - $R -e "library('ragtop')"           # [not win]
    - "\"%R%\" -e \"library('ragtop')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ragtop
  license: GPL-2.0-or-later
  summary: Algorithms to price American and European equity options, convertible bonds and a
    variety of other financial derivatives. It uses an extension of the usual Black-Scholes
    model in which jump to default may occur at a probability specified by a power-law
    link between stock price and hazard rate as found in the paper by Takahashi, Kobayashi,
    and Nakagawa (2001) <doi:10.3905/jfi.2001.319302>.  We use ideas and techniques
    from Andersen and Buffum (2002) <doi:10.2139/ssrn.355308> and Linetsky (2006) <doi:10.1111/j.1467-9965.2006.00271.x>.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - TanguyGen

# Package: ragtop
# Type: Package
# Title: Pricing Equity Derivatives with Extensions of Black-Scholes
# Version: 1.1.1
# Date: 2020-02-29
# Author: Brian K. Boonstra
# Maintainer: Brian K. Boonstra <ragtop@boonstra.org>
# Description: Algorithms to price American and European equity options, convertible bonds and a variety of other financial derivatives. It uses an extension of the usual Black-Scholes model in which jump to default may occur at a probability specified by a power-law link between stock price and hazard rate as found in the paper by Takahashi, Kobayashi, and Nakagawa (2001) <doi:10.3905/jfi.2001.319302>.  We use ideas and techniques from Andersen and Buffum (2002) <doi:10.2139/ssrn.355308> and Linetsky (2006) <doi:10.1111/j.1467-9965.2006.00271.x>.
# Depends: limSolve (>= 1.5.5.1), futile.logger (>= 1.4.1), R (>= 2.10), methods (>= 3.2.2)
# Suggests: testthat, roxygen2, knitr, rmarkdown, reshape2, stringr, ggplot2, MASS, RColorBrewer, BondValuation, R.cache, Quandl
# License: GPL (>= 2)
# Encoding: UTF-8
# LazyData: TRUE
# VignetteBuilder: knitr
# RoxygenNote: 7.0.2
# NeedsCompilation: no
# Packaged: 2020-03-03 03:48:55 UTC; brian
# Repository: CRAN
# Date/Publication: 2020-03-03 09:00:02 UTC
